# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunOperationgUi5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

# 前端UI部分
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1710, 943)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridlayout = QtWidgets.QGridLayout(self.mainFrame)
        self.gridlayout.setObjectName("gridlayout")
        self.targetlineEdit = QtWidgets.QLineEdit(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetlineEdit.sizePolicy().hasHeightForWidth())
        self.targetlineEdit.setSizePolicy(sizePolicy)
        self.targetlineEdit.setObjectName("targetlineEdit")
        self.gridlayout.addWidget(self.targetlineEdit, 0, 3, 1, 2)
        self.payloadCombo = QtWidgets.QComboBox(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadCombo.sizePolicy().hasHeightForWidth())
        self.payloadCombo.setSizePolicy(sizePolicy)
        self.payloadCombo.setEditable(True)
        self.payloadCombo.setObjectName("payloadCombo")
        self.gridlayout.addWidget(self.payloadCombo, 0, 1, 1, 1)
        self.emptyButton = QtWidgets.QPushButton(self.mainFrame)
        self.emptyButton.setObjectName("emptyButton")
        self.gridlayout.addWidget(self.emptyButton, 0, 6, 1, 1)
        self.payloadLabel = QtWidgets.QLabel(self.mainFrame)
        self.payloadLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.payloadLabel.setObjectName("payloadLabel")
        self.gridlayout.addWidget(self.payloadLabel, 0, 0, 1, 1)
        self.CheckButton = QtWidgets.QPushButton(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckButton.sizePolicy().hasHeightForWidth())
        self.CheckButton.setSizePolicy(sizePolicy)
        self.CheckButton.setObjectName("CheckButton")
        self.gridlayout.addWidget(self.CheckButton, 0, 5, 1, 1)
        self.targetLabel = QtWidgets.QLabel(self.mainFrame)
        self.targetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.gridlayout.addWidget(self.targetLabel, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.mainFrame, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ipaddrLabel = QtWidgets.QLabel(self.frame)
        self.ipaddrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel.setObjectName("ipaddrLabel")
        self.horizontalLayout_2.addWidget(self.ipaddrLabel)
        self.lipaddrlineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lipaddrlineEdit.sizePolicy().hasHeightForWidth())
        self.lipaddrlineEdit.setSizePolicy(sizePolicy)
        self.lipaddrlineEdit.setObjectName("lipaddrlineEdit")
        self.horizontalLayout_2.addWidget(self.lipaddrlineEdit)
        self.lportLabel = QtWidgets.QLabel(self.frame)
        self.lportLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lportLabel.setObjectName("lportLabel")
        self.horizontalLayout_2.addWidget(self.lportLabel)
        self.lport = QtWidgets.QLineEdit(self.frame)
        self.lport.setObjectName("lport")
        self.horizontalLayout_2.addWidget(self.lport)
        self.reboundLabel = QtWidgets.QLabel(self.frame)
        self.reboundLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reboundLabel.setObjectName("reboundLabel")
        self.horizontalLayout_2.addWidget(self.reboundLabel)
        self.reboundCombo = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.reboundCombo.sizePolicy().hasHeightForWidth())
        self.reboundCombo.setSizePolicy(sizePolicy)
        self.reboundCombo.setEditable(True)
        self.reboundCombo.setObjectName("reboundCombo")
        self.horizontalLayout_2.addWidget(self.reboundCombo)
        self.reboundButton = QtWidgets.QPushButton(self.frame)
        self.reboundButton.setObjectName("reboundButton")
        self.horizontalLayout_2.addWidget(self.reboundButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.socketLabel = QtWidgets.QLabel(self.frame)
        self.socketLabel.setObjectName("socketLabel")
        self.horizontalLayout_4.addWidget(self.socketLabel)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_4.addWidget(self.line_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.localListenIpaddrLabel = QtWidgets.QLabel(self.frame)
        self.localListenIpaddrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.localListenIpaddrLabel.setObjectName("localListenIpaddrLabel")
        self.horizontalLayout_3.addWidget(self.localListenIpaddrLabel)
        self.localListenEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit.sizePolicy().hasHeightForWidth())
        self.localListenEdit.setSizePolicy(sizePolicy)
        self.localListenEdit.setObjectName("localListenEdit")
        self.horizontalLayout_3.addWidget(self.localListenEdit)
        self.localListenPort = QtWidgets.QLabel(self.frame)
        self.localListenPort.setObjectName("localListenPort")
        self.horizontalLayout_3.addWidget(self.localListenPort)
        self.localListenPortEdit = QtWidgets.QLineEdit(self.frame)
        self.localListenPortEdit.setObjectName("localListenPortEdit")
        self.horizontalLayout_3.addWidget(self.localListenPortEdit)
        self.startSocketButton = QtWidgets.QPushButton(self.frame)
        self.startSocketButton.setObjectName("startSocketButton")
        self.horizontalLayout_3.addWidget(self.startSocketButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.basicInfoTextEdit = QtWidgets.QTextEdit(self.tab)
        self.basicInfoTextEdit.setOverwriteMode(True)
        self.basicInfoTextEdit.setObjectName("basicInfoTextEdit")
        self.verticalLayout.addWidget(self.basicInfoTextEdit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commandLabel = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel.sizePolicy().hasHeightForWidth())
        self.commandLabel.setSizePolicy(sizePolicy)
        self.commandLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel.setObjectName("commandLabel")
        self.horizontalLayout.addWidget(self.commandLabel)
        self.commandCombo = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo.sizePolicy().hasHeightForWidth())
        self.commandCombo.setSizePolicy(sizePolicy)
        self.commandCombo.setEditable(True)
        self.commandCombo.setObjectName("commandCombo")
        self.horizontalLayout.addWidget(self.commandCombo)
        self.commondButton = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton.sizePolicy().hasHeightForWidth())
        self.commondButton.setSizePolicy(sizePolicy)
        self.commondButton.setObjectName("commondButton")
        self.horizontalLayout.addWidget(self.commondButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.commandBasicInfoTextEdit = QtWidgets.QTextEdit(self.tab_2)
        self.commandBasicInfoTextEdit.setOverwriteMode(True)
        self.commandBasicInfoTextEdit.setObjectName("commandBasicInfoTextEdit")
        self.verticalLayout_2.addWidget(self.commandBasicInfoTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.commandLabel_2 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_2.sizePolicy().hasHeightForWidth())
        self.commandLabel_2.setSizePolicy(sizePolicy)
        self.commandLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_2.setObjectName("commandLabel_2")
        self.horizontalLayout_5.addWidget(self.commandLabel_2)
        self.localListenEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_2.sizePolicy().hasHeightForWidth())
        self.localListenEdit_2.setSizePolicy(sizePolicy)
        self.localListenEdit_2.setObjectName("localListenEdit_2")
        self.horizontalLayout_5.addWidget(self.localListenEdit_2)
        self.checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.commondButton_2 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_2.sizePolicy().hasHeightForWidth())
        self.commondButton_2.setSizePolicy(sizePolicy)
        self.commondButton_2.setObjectName("commondButton_2")
        self.horizontalLayout_5.addWidget(self.commondButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.commandBasicInfoTextEdit_2 = QtWidgets.QTextEdit(self.tab_3)
        self.commandBasicInfoTextEdit_2.setEnabled(True)
        self.commandBasicInfoTextEdit_2.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_2.setObjectName("commandBasicInfoTextEdit_2")
        self.verticalLayout_5.addWidget(self.commandBasicInfoTextEdit_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.commandLabel_3 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_3.sizePolicy().hasHeightForWidth())
        self.commandLabel_3.setSizePolicy(sizePolicy)
        self.commandLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_3.setObjectName("commandLabel_3")
        self.horizontalLayout_6.addWidget(self.commandLabel_3)
        self.commandCombo_3 = QtWidgets.QComboBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo_3.sizePolicy().hasHeightForWidth())
        self.commandCombo_3.setSizePolicy(sizePolicy)
        self.commandCombo_3.setEditable(True)
        self.commandCombo_3.setObjectName("commandCombo_3")
        self.horizontalLayout_6.addWidget(self.commandCombo_3)
        self.commandLabel_4 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_4.sizePolicy().hasHeightForWidth())
        self.commandLabel_4.setSizePolicy(sizePolicy)
        self.commandLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_4.setObjectName("commandLabel_4")
        self.horizontalLayout_6.addWidget(self.commandLabel_4)
        self.localListenEdit_3 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_3.sizePolicy().hasHeightForWidth())
        self.localListenEdit_3.setSizePolicy(sizePolicy)
        self.localListenEdit_3.setObjectName("localListenEdit_3")
        self.horizontalLayout_6.addWidget(self.localListenEdit_3)
        self.commondButton_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_4.sizePolicy().hasHeightForWidth())
        self.commondButton_4.setSizePolicy(sizePolicy)
        self.commondButton_4.setObjectName("commondButton_4")
        self.horizontalLayout_6.addWidget(self.commondButton_4)
        self.commondButton_6 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_6.sizePolicy().hasHeightForWidth())
        self.commondButton_6.setSizePolicy(sizePolicy)
        self.commondButton_6.setObjectName("commondButton_6")
        self.horizontalLayout_6.addWidget(self.commondButton_6)
        self.commondButton_3 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_3.sizePolicy().hasHeightForWidth())
        self.commondButton_3.setSizePolicy(sizePolicy)
        self.commondButton_3.setObjectName("commondButton_3")
        self.horizontalLayout_6.addWidget(self.commondButton_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.commandBasicInfoTextEdit_3 = QtWidgets.QTextEdit(self.tab_4)
        self.commandBasicInfoTextEdit_3.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_3.setObjectName("commandBasicInfoTextEdit_3")
        self.verticalLayout_6.addWidget(self.commandBasicInfoTextEdit_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1710, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.targetLabel.setBuddy(self.payloadCombo)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CVE-2020-5902-RCE-Big漏洞利用工具HW版v1.0-毕加索实验室-by Rocky 20200710 By T00ls.Net" ))
        self.targetlineEdit.setPlaceholderText(_translate("MainWindow", "https://192.168.50.122"))
        self.payloadCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.emptyButton.setText(_translate("MainWindow", "清空日志"))
        self.payloadLabel.setText(_translate("MainWindow", "攻击载核:"))
        self.CheckButton.setText(_translate("MainWindow", "检查"))
        self.targetLabel.setText(_translate("MainWindow", "目标地址:"))
        self.ipaddrLabel.setText(_translate("MainWindow", "回连IP:"))
        self.lportLabel.setText(_translate("MainWindow", "端口:"))
        self.reboundLabel.setText(_translate("MainWindow", "反弹方式:"))
        self.reboundCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.reboundButton.setText(_translate("MainWindow", "执行反弹"))
        self.socketLabel.setText(_translate("MainWindow", "                                            SOCKET代理"))
        self.localListenIpaddrLabel.setText(_translate("MainWindow", "本地监听地址："))
        self.localListenPort.setText(_translate("MainWindow", "本地监听端口"))
        self.startSocketButton.setText(_translate("MainWindow", "开启"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "基本信息"))
        self.commandLabel.setText(_translate("MainWindow", "命令执行:"))
        self.commandCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commondButton.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "命令执行"))
        self.commandLabel_2.setText(_translate("MainWindow", "文件路径:"))
        self.checkBox.setText(_translate("MainWindow", "自定义路径"))
        self.commondButton_2.setText(_translate("MainWindow", "上传文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "文件上传"))
        self.commandLabel_3.setText(_translate("MainWindow", "线程："))
        self.commandCombo_3.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commandLabel_4.setText(_translate("MainWindow", "文件路径:"))
        self.commondButton_4.setText(_translate("MainWindow", "导入"))
        self.commondButton_6.setText(_translate("MainWindow", "开始"))
        self.commondButton_3.setText(_translate("MainWindow", "停止"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "批量验证"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
