# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OperatingUi-new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1667, 860)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        item_0.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        item_0.setFont(0, font)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.mainFrame = QtWidgets.QFrame(self.tab_3)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridlayout = QtWidgets.QGridLayout(self.mainFrame)
        self.gridlayout.setObjectName("gridlayout")
        self.targetlineEdit = QtWidgets.QLineEdit(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetlineEdit.sizePolicy().hasHeightForWidth())
        self.targetlineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.targetlineEdit.setFont(font)
        self.targetlineEdit.setObjectName("targetlineEdit")
        self.gridlayout.addWidget(self.targetlineEdit, 0, 3, 1, 2)
        self.targetLabel = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.targetLabel.setFont(font)
        self.targetLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.gridlayout.addWidget(self.targetLabel, 0, 2, 1, 1)
        self.payloadLabel = QtWidgets.QLabel(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.payloadLabel.setFont(font)
        self.payloadLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.payloadLabel.setObjectName("payloadLabel")
        self.gridlayout.addWidget(self.payloadLabel, 0, 0, 1, 1)
        self.payloadCombo = QtWidgets.QComboBox(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadCombo.sizePolicy().hasHeightForWidth())
        self.payloadCombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.payloadCombo.setFont(font)
        self.payloadCombo.setEditable(True)
        self.payloadCombo.setObjectName("payloadCombo")
        self.gridlayout.addWidget(self.payloadCombo, 0, 1, 1, 1)
        self.emptyButton = QtWidgets.QPushButton(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.emptyButton.setFont(font)
        self.emptyButton.setObjectName("emptyButton")
        self.gridlayout.addWidget(self.emptyButton, 0, 6, 1, 1)
        self.CheckButton = QtWidgets.QPushButton(self.mainFrame)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.CheckButton.setFont(font)
        self.CheckButton.setObjectName("CheckButton")
        self.gridlayout.addWidget(self.CheckButton, 0, 5, 1, 1)
        self.verticalLayout_7.addWidget(self.mainFrame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ipaddrLabel = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ipaddrLabel.setFont(font)
        self.ipaddrLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel.setObjectName("ipaddrLabel")
        self.horizontalLayout_2.addWidget(self.ipaddrLabel)
        self.lipaddrlineEdit = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lipaddrlineEdit.sizePolicy().hasHeightForWidth())
        self.lipaddrlineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.lipaddrlineEdit.setFont(font)
        self.lipaddrlineEdit.setObjectName("lipaddrlineEdit")
        self.horizontalLayout_2.addWidget(self.lipaddrlineEdit)
        self.lportLabel = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.lportLabel.setFont(font)
        self.lportLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lportLabel.setObjectName("lportLabel")
        self.horizontalLayout_2.addWidget(self.lportLabel)
        self.lport = QtWidgets.QLineEdit(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.lport.setFont(font)
        self.lport.setObjectName("lport")
        self.horizontalLayout_2.addWidget(self.lport)
        self.reboundLabel = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.reboundLabel.setFont(font)
        self.reboundLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reboundLabel.setObjectName("reboundLabel")
        self.horizontalLayout_2.addWidget(self.reboundLabel)
        self.reboundCombo = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.reboundCombo.sizePolicy().hasHeightForWidth())
        self.reboundCombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.reboundCombo.setFont(font)
        self.reboundCombo.setEditable(True)
        self.reboundCombo.setObjectName("reboundCombo")
        self.horizontalLayout_2.addWidget(self.reboundCombo)
        self.reboundButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.reboundButton.setFont(font)
        self.reboundButton.setObjectName("reboundButton")
        self.horizontalLayout_2.addWidget(self.reboundButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.basicInfoTextEdit = QtWidgets.QTextEdit(self.tab_8)
        self.basicInfoTextEdit.setOverwriteMode(True)
        self.basicInfoTextEdit.setObjectName("basicInfoTextEdit")
        self.verticalLayout.addWidget(self.basicInfoTextEdit)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commandLabel = QtWidgets.QLabel(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel.sizePolicy().hasHeightForWidth())
        self.commandLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        self.commandLabel.setFont(font)
        self.commandLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel.setObjectName("commandLabel")
        self.horizontalLayout.addWidget(self.commandLabel)
        self.commandCombo = QtWidgets.QComboBox(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo.sizePolicy().hasHeightForWidth())
        self.commandCombo.setSizePolicy(sizePolicy)
        self.commandCombo.setEditable(True)
        self.commandCombo.setObjectName("commandCombo")
        self.horizontalLayout.addWidget(self.commandCombo)
        self.commondButton = QtWidgets.QPushButton(self.tab_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton.sizePolicy().hasHeightForWidth())
        self.commondButton.setSizePolicy(sizePolicy)
        self.commondButton.setObjectName("commondButton")
        self.horizontalLayout.addWidget(self.commondButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.commandBasicInfoTextEdit = QtWidgets.QTextEdit(self.tab_9)
        self.commandBasicInfoTextEdit.setAccessibleDescription("")
        self.commandBasicInfoTextEdit.setOverwriteMode(True)
        self.commandBasicInfoTextEdit.setPlaceholderText("")
        self.commandBasicInfoTextEdit.setObjectName("commandBasicInfoTextEdit")
        self.verticalLayout_2.addWidget(self.commandBasicInfoTextEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.commandLabel_2 = QtWidgets.QLabel(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_2.sizePolicy().hasHeightForWidth())
        self.commandLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(12)
        self.commandLabel_2.setFont(font)
        self.commandLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_2.setObjectName("commandLabel_2")
        self.horizontalLayout_5.addWidget(self.commandLabel_2)
        self.filePathEdit = QtWidgets.QLineEdit(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathEdit.sizePolicy().hasHeightForWidth())
        self.filePathEdit.setSizePolicy(sizePolicy)
        self.filePathEdit.setObjectName("filePathEdit")
        self.horizontalLayout_5.addWidget(self.filePathEdit)
        self.checkBox = QtWidgets.QCheckBox(self.tab_10)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        self.uploadFilesbutton = QtWidgets.QPushButton(self.tab_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadFilesbutton.sizePolicy().hasHeightForWidth())
        self.uploadFilesbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadFilesbutton.setFont(font)
        self.uploadFilesbutton.setObjectName("uploadFilesbutton")
        self.horizontalLayout_5.addWidget(self.uploadFilesbutton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.commandBasicInfoTextEdit_2 = QtWidgets.QTextEdit(self.tab_10)
        self.commandBasicInfoTextEdit_2.setEnabled(True)
        self.commandBasicInfoTextEdit_2.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_2.setObjectName("commandBasicInfoTextEdit_2")
        self.verticalLayout_5.addWidget(self.commandBasicInfoTextEdit_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_11)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.commandLabel_3 = QtWidgets.QLabel(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_3.sizePolicy().hasHeightForWidth())
        self.commandLabel_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(12)
        self.commandLabel_3.setFont(font)
        self.commandLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_3.setObjectName("commandLabel_3")
        self.horizontalLayout_6.addWidget(self.commandLabel_3)
        self.threads_num = QtWidgets.QComboBox(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threads_num.sizePolicy().hasHeightForWidth())
        self.threads_num.setSizePolicy(sizePolicy)
        self.threads_num.setEditable(True)
        self.threads_num.setObjectName("threads_num")
        self.horizontalLayout_6.addWidget(self.threads_num)
        self.commandLabel_4 = QtWidgets.QLabel(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_4.sizePolicy().hasHeightForWidth())
        self.commandLabel_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(12)
        self.commandLabel_4.setFont(font)
        self.commandLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_4.setObjectName("commandLabel_4")
        self.horizontalLayout_6.addWidget(self.commandLabel_4)
        self.importFilePath = QtWidgets.QLineEdit(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importFilePath.sizePolicy().hasHeightForWidth())
        self.importFilePath.setSizePolicy(sizePolicy)
        self.importFilePath.setObjectName("importFilePath")
        self.horizontalLayout_6.addWidget(self.importFilePath)
        self.importButton = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(12)
        self.importButton.setFont(font)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_6.addWidget(self.importButton)
        self.startCheckButton = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startCheckButton.sizePolicy().hasHeightForWidth())
        self.startCheckButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(12)
        self.startCheckButton.setFont(font)
        self.startCheckButton.setObjectName("startCheckButton")
        self.horizontalLayout_6.addWidget(self.startCheckButton)
        self.stopCheckButton = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopCheckButton.sizePolicy().hasHeightForWidth())
        self.stopCheckButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Heiti SC")
        font.setPointSize(12)
        self.stopCheckButton.setFont(font)
        self.stopCheckButton.setObjectName("stopCheckButton")
        self.horizontalLayout_6.addWidget(self.stopCheckButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.commandBasicInfoTextEdit_3 = QtWidgets.QTextEdit(self.tab_11)
        self.commandBasicInfoTextEdit_3.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_3.setObjectName("commandBasicInfoTextEdit_3")
        self.verticalLayout_6.addWidget(self.commandBasicInfoTextEdit_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget_2.addTab(self.tab_11, "")
        self.verticalLayout_7.addWidget(self.tabWidget_2)
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mainFrame_3 = QtWidgets.QFrame(self.tab_4)
        self.mainFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame_3.setObjectName("mainFrame_3")
        self._3 = QtWidgets.QGridLayout(self.mainFrame_3)
        self._3.setObjectName("_3")
        self.targetlineEdit_2 = QtWidgets.QLineEdit(self.mainFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetlineEdit_2.sizePolicy().hasHeightForWidth())
        self.targetlineEdit_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.targetlineEdit_2.setFont(font)
        self.targetlineEdit_2.setObjectName("targetlineEdit_2")
        self._3.addWidget(self.targetlineEdit_2, 0, 3, 1, 2)
        self.targetLabel_3 = QtWidgets.QLabel(self.mainFrame_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.targetLabel_3.setFont(font)
        self.targetLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel_3.setObjectName("targetLabel_3")
        self._3.addWidget(self.targetLabel_3, 0, 2, 1, 1)
        self.emptyButton_2 = QtWidgets.QPushButton(self.mainFrame_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.emptyButton_2.setFont(font)
        self.emptyButton_2.setObjectName("emptyButton_2")
        self._3.addWidget(self.emptyButton_2, 0, 6, 1, 1)
        self.CheckButton_2 = QtWidgets.QPushButton(self.mainFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckButton_2.sizePolicy().hasHeightForWidth())
        self.CheckButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.CheckButton_2.setFont(font)
        self.CheckButton_2.setObjectName("CheckButton_2")
        self._3.addWidget(self.CheckButton_2, 0, 5, 1, 1)
        self.payloadCombo_2 = QtWidgets.QComboBox(self.mainFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadCombo_2.sizePolicy().hasHeightForWidth())
        self.payloadCombo_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.payloadCombo_2.setFont(font)
        self.payloadCombo_2.setEditable(True)
        self.payloadCombo_2.setObjectName("payloadCombo_2")
        self._3.addWidget(self.payloadCombo_2, 0, 1, 1, 1)
        self.payloadLabel_2 = QtWidgets.QLabel(self.mainFrame_3)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(13)
        self.payloadLabel_2.setFont(font)
        self.payloadLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.payloadLabel_2.setObjectName("payloadLabel_2")
        self._3.addWidget(self.payloadLabel_2, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.mainFrame_3)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_21)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.basicInfoTextEdit_2 = QtWidgets.QTextEdit(self.tab_21)
        self.basicInfoTextEdit_2.setOverwriteMode(True)
        self.basicInfoTextEdit_2.setObjectName("basicInfoTextEdit_2")
        self.verticalLayout_12.addWidget(self.basicInfoTextEdit_2)
        self.tabWidget_3.addTab(self.tab_21, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_23)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.commandLabel_10 = QtWidgets.QLabel(self.tab_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_10.sizePolicy().hasHeightForWidth())
        self.commandLabel_10.setSizePolicy(sizePolicy)
        self.commandLabel_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_10.setObjectName("commandLabel_10")
        self.horizontalLayout_14.addWidget(self.commandLabel_10)
        self.filePathEdit_2 = QtWidgets.QLineEdit(self.tab_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathEdit_2.sizePolicy().hasHeightForWidth())
        self.filePathEdit_2.setSizePolicy(sizePolicy)
        self.filePathEdit_2.setObjectName("filePathEdit_2")
        self.horizontalLayout_14.addWidget(self.filePathEdit_2)
        self.commandLabel_21 = QtWidgets.QLabel(self.tab_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_21.sizePolicy().hasHeightForWidth())
        self.commandLabel_21.setSizePolicy(sizePolicy)
        self.commandLabel_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_21.setObjectName("commandLabel_21")
        self.horizontalLayout_14.addWidget(self.commandLabel_21)
        self.filename = QtWidgets.QLineEdit(self.tab_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename.sizePolicy().hasHeightForWidth())
        self.filename.setSizePolicy(sizePolicy)
        self.filename.setMaximumSize(QtCore.QSize(200, 200))
        self.filename.setObjectName("filename")
        self.horizontalLayout_14.addWidget(self.filename)
        self.uploadFilesbutton_2 = QtWidgets.QPushButton(self.tab_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadFilesbutton_2.sizePolicy().hasHeightForWidth())
        self.uploadFilesbutton_2.setSizePolicy(sizePolicy)
        self.uploadFilesbutton_2.setObjectName("uploadFilesbutton_2")
        self.horizontalLayout_14.addWidget(self.uploadFilesbutton_2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.commandBasicInfoTextEdit_2_2 = QtWidgets.QTextEdit(self.tab_23)
        self.commandBasicInfoTextEdit_2_2.setEnabled(True)
        self.commandBasicInfoTextEdit_2_2.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_2_2.setObjectName("commandBasicInfoTextEdit_2_2")
        self.verticalLayout_13.addWidget(self.commandBasicInfoTextEdit_2_2)
        self.horizontalLayout_15.addLayout(self.verticalLayout_13)
        self.tabWidget_3.addTab(self.tab_23, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_24)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.commandLabel_11 = QtWidgets.QLabel(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_11.sizePolicy().hasHeightForWidth())
        self.commandLabel_11.setSizePolicy(sizePolicy)
        self.commandLabel_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_11.setObjectName("commandLabel_11")
        self.horizontalLayout_17.addWidget(self.commandLabel_11)
        self.threads_num_2 = QtWidgets.QComboBox(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threads_num_2.sizePolicy().hasHeightForWidth())
        self.threads_num_2.setSizePolicy(sizePolicy)
        self.threads_num_2.setEditable(True)
        self.threads_num_2.setObjectName("threads_num_2")
        self.horizontalLayout_17.addWidget(self.threads_num_2)
        self.commandLabel_12 = QtWidgets.QLabel(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_12.sizePolicy().hasHeightForWidth())
        self.commandLabel_12.setSizePolicy(sizePolicy)
        self.commandLabel_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_12.setObjectName("commandLabel_12")
        self.horizontalLayout_17.addWidget(self.commandLabel_12)
        self.importFilePath_2 = QtWidgets.QLineEdit(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importFilePath_2.sizePolicy().hasHeightForWidth())
        self.importFilePath_2.setSizePolicy(sizePolicy)
        self.importFilePath_2.setObjectName("importFilePath_2")
        self.horizontalLayout_17.addWidget(self.importFilePath_2)
        self.importButton_2 = QtWidgets.QPushButton(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton_2.sizePolicy().hasHeightForWidth())
        self.importButton_2.setSizePolicy(sizePolicy)
        self.importButton_2.setObjectName("importButton_2")
        self.horizontalLayout_17.addWidget(self.importButton_2)
        self.startCheckButton_2 = QtWidgets.QPushButton(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startCheckButton_2.sizePolicy().hasHeightForWidth())
        self.startCheckButton_2.setSizePolicy(sizePolicy)
        self.startCheckButton_2.setObjectName("startCheckButton_2")
        self.horizontalLayout_17.addWidget(self.startCheckButton_2)
        self.stopCheckButton_2 = QtWidgets.QPushButton(self.tab_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopCheckButton_2.sizePolicy().hasHeightForWidth())
        self.stopCheckButton_2.setSizePolicy(sizePolicy)
        self.stopCheckButton_2.setObjectName("stopCheckButton_2")
        self.horizontalLayout_17.addWidget(self.stopCheckButton_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.commandBasicInfoTextEdit_3_2 = QtWidgets.QTextEdit(self.tab_24)
        self.commandBasicInfoTextEdit_3_2.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_3_2.setObjectName("commandBasicInfoTextEdit_3_2")
        self.verticalLayout_16.addWidget(self.commandBasicInfoTextEdit_3_2)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.tabWidget_3.addTab(self.tab_24, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.decVule = QtWidgets.QPushButton(self.tab)
        self.decVule.setMaximumSize(QtCore.QSize(250, 250))
        self.decVule.setObjectName("decVule")
        self.horizontalLayout_13.addWidget(self.decVule)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.commandBasicInfoTextEdit_4_2 = QtWidgets.QTextEdit(self.tab)
        self.commandBasicInfoTextEdit_4_2.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_4_2.setObjectName("commandBasicInfoTextEdit_4_2")
        self.verticalLayout_11.addWidget(self.commandBasicInfoTextEdit_4_2)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.tabWidget_3.addTab(self.tab, "")
        self.verticalLayout_8.addWidget(self.tabWidget_3)
        self.textEdit_2_2 = QtWidgets.QTextEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit_2_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.textEdit_2_2.setFont(font)
        self.textEdit_2_2.setObjectName("textEdit_2_2")
        self.verticalLayout_8.addWidget(self.textEdit_2_2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.mainFrame_4 = QtWidgets.QFrame(self.tab_5)
        self.mainFrame_4.setGeometry(QtCore.QRect(10, 7, 1181, 48))
        self.mainFrame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame_4.setObjectName("mainFrame_4")
        self._4 = QtWidgets.QGridLayout(self.mainFrame_4)
        self._4.setObjectName("_4")
        self.targetlineEdit_4 = QtWidgets.QLineEdit(self.mainFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetlineEdit_4.sizePolicy().hasHeightForWidth())
        self.targetlineEdit_4.setSizePolicy(sizePolicy)
        self.targetlineEdit_4.setObjectName("targetlineEdit_4")
        self._4.addWidget(self.targetlineEdit_4, 0, 3, 1, 2)
        self.payloadCombo_4 = QtWidgets.QComboBox(self.mainFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadCombo_4.sizePolicy().hasHeightForWidth())
        self.payloadCombo_4.setSizePolicy(sizePolicy)
        self.payloadCombo_4.setEditable(True)
        self.payloadCombo_4.setObjectName("payloadCombo_4")
        self._4.addWidget(self.payloadCombo_4, 0, 1, 1, 1)
        self.emptyButton_4 = QtWidgets.QPushButton(self.mainFrame_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.emptyButton_4.setFont(font)
        self.emptyButton_4.setObjectName("emptyButton_4")
        self._4.addWidget(self.emptyButton_4, 0, 6, 1, 1)
        self.payloadLabel_4 = QtWidgets.QLabel(self.mainFrame_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.payloadLabel_4.setFont(font)
        self.payloadLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.payloadLabel_4.setObjectName("payloadLabel_4")
        self._4.addWidget(self.payloadLabel_4, 0, 0, 1, 1)
        self.CheckButton_4 = QtWidgets.QPushButton(self.mainFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckButton_4.sizePolicy().hasHeightForWidth())
        self.CheckButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.CheckButton_4.setFont(font)
        self.CheckButton_4.setObjectName("CheckButton_4")
        self._4.addWidget(self.CheckButton_4, 0, 5, 1, 1)
        self.targetLabel_4 = QtWidgets.QLabel(self.mainFrame_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.targetLabel_4.setFont(font)
        self.targetLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel_4.setObjectName("targetLabel_4")
        self._4.addWidget(self.targetLabel_4, 0, 2, 1, 1)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_5.setGeometry(QtCore.QRect(10, 147, 1181, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget_5.sizePolicy().hasHeightForWidth())
        self.tabWidget_5.setSizePolicy(sizePolicy)
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_25)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.basicInfoTextEdit_4 = QtWidgets.QTextEdit(self.tab_25)
        self.basicInfoTextEdit_4.setOverwriteMode(True)
        self.basicInfoTextEdit_4.setObjectName("basicInfoTextEdit_4")
        self.verticalLayout_17.addWidget(self.basicInfoTextEdit_4)
        self.tabWidget_5.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab_26)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.commandLabel_13 = QtWidgets.QLabel(self.tab_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_13.sizePolicy().hasHeightForWidth())
        self.commandLabel_13.setSizePolicy(sizePolicy)
        self.commandLabel_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_13.setObjectName("commandLabel_13")
        self.horizontalLayout_19.addWidget(self.commandLabel_13)
        self.commandCombo_7 = QtWidgets.QComboBox(self.tab_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo_7.sizePolicy().hasHeightForWidth())
        self.commandCombo_7.setSizePolicy(sizePolicy)
        self.commandCombo_7.setEditable(True)
        self.commandCombo_7.setObjectName("commandCombo_7")
        self.horizontalLayout_19.addWidget(self.commandCombo_7)
        self.commondButton_16 = QtWidgets.QPushButton(self.tab_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_16.sizePolicy().hasHeightForWidth())
        self.commondButton_16.setSizePolicy(sizePolicy)
        self.commondButton_16.setObjectName("commondButton_16")
        self.horizontalLayout_19.addWidget(self.commondButton_16)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.commandBasicInfoTextEdit_10 = QtWidgets.QTextEdit(self.tab_26)
        self.commandBasicInfoTextEdit_10.setAccessibleDescription("")
        self.commandBasicInfoTextEdit_10.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_10.setPlaceholderText("")
        self.commandBasicInfoTextEdit_10.setObjectName("commandBasicInfoTextEdit_10")
        self.verticalLayout_19.addWidget(self.commandBasicInfoTextEdit_10)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.tabWidget_5.addTab(self.tab_26, "")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.tab_27)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.commandLabel_14 = QtWidgets.QLabel(self.tab_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_14.sizePolicy().hasHeightForWidth())
        self.commandLabel_14.setSizePolicy(sizePolicy)
        self.commandLabel_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_14.setObjectName("commandLabel_14")
        self.horizontalLayout_21.addWidget(self.commandLabel_14)
        self.localListenEdit_8 = QtWidgets.QLineEdit(self.tab_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_8.sizePolicy().hasHeightForWidth())
        self.localListenEdit_8.setSizePolicy(sizePolicy)
        self.localListenEdit_8.setObjectName("localListenEdit_8")
        self.horizontalLayout_21.addWidget(self.localListenEdit_8)
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_27)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_21.addWidget(self.checkBox_4)
        self.commondButton_17 = QtWidgets.QPushButton(self.tab_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_17.sizePolicy().hasHeightForWidth())
        self.commondButton_17.setSizePolicy(sizePolicy)
        self.commondButton_17.setObjectName("commondButton_17")
        self.horizontalLayout_21.addWidget(self.commondButton_17)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        self.commandBasicInfoTextEdit_11 = QtWidgets.QTextEdit(self.tab_27)
        self.commandBasicInfoTextEdit_11.setEnabled(True)
        self.commandBasicInfoTextEdit_11.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_11.setObjectName("commandBasicInfoTextEdit_11")
        self.verticalLayout_20.addWidget(self.commandBasicInfoTextEdit_11)
        self.horizontalLayout_20.addLayout(self.verticalLayout_20)
        self.tabWidget_5.addTab(self.tab_27, "")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.tab_28)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.commandLabel_15 = QtWidgets.QLabel(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_15.sizePolicy().hasHeightForWidth())
        self.commandLabel_15.setSizePolicy(sizePolicy)
        self.commandLabel_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_15.setObjectName("commandLabel_15")
        self.horizontalLayout_23.addWidget(self.commandLabel_15)
        self.commandCombo_8 = QtWidgets.QComboBox(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo_8.sizePolicy().hasHeightForWidth())
        self.commandCombo_8.setSizePolicy(sizePolicy)
        self.commandCombo_8.setEditable(True)
        self.commandCombo_8.setObjectName("commandCombo_8")
        self.horizontalLayout_23.addWidget(self.commandCombo_8)
        self.commandLabel_16 = QtWidgets.QLabel(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_16.sizePolicy().hasHeightForWidth())
        self.commandLabel_16.setSizePolicy(sizePolicy)
        self.commandLabel_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_16.setObjectName("commandLabel_16")
        self.horizontalLayout_23.addWidget(self.commandLabel_16)
        self.localListenEdit_9 = QtWidgets.QLineEdit(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_9.sizePolicy().hasHeightForWidth())
        self.localListenEdit_9.setSizePolicy(sizePolicy)
        self.localListenEdit_9.setObjectName("localListenEdit_9")
        self.horizontalLayout_23.addWidget(self.localListenEdit_9)
        self.commondButton_18 = QtWidgets.QPushButton(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_18.sizePolicy().hasHeightForWidth())
        self.commondButton_18.setSizePolicy(sizePolicy)
        self.commondButton_18.setObjectName("commondButton_18")
        self.horizontalLayout_23.addWidget(self.commondButton_18)
        self.commondButton_19 = QtWidgets.QPushButton(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_19.sizePolicy().hasHeightForWidth())
        self.commondButton_19.setSizePolicy(sizePolicy)
        self.commondButton_19.setObjectName("commondButton_19")
        self.horizontalLayout_23.addWidget(self.commondButton_19)
        self.commondButton_20 = QtWidgets.QPushButton(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_20.sizePolicy().hasHeightForWidth())
        self.commondButton_20.setSizePolicy(sizePolicy)
        self.commondButton_20.setObjectName("commondButton_20")
        self.horizontalLayout_23.addWidget(self.commondButton_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_23)
        self.commandBasicInfoTextEdit_12 = QtWidgets.QTextEdit(self.tab_28)
        self.commandBasicInfoTextEdit_12.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_12.setObjectName("commandBasicInfoTextEdit_12")
        self.verticalLayout_21.addWidget(self.commandBasicInfoTextEdit_12)
        self.horizontalLayout_22.addLayout(self.verticalLayout_21)
        self.tabWidget_5.addTab(self.tab_28, "")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 577, 1181, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit_4.sizePolicy().hasHeightForWidth())
        self.textEdit_4.setSizePolicy(sizePolicy)
        self.textEdit_4.setObjectName("textEdit_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 70, 1181, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.ipaddrLabel_4 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.ipaddrLabel_4.setFont(font)
        self.ipaddrLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel_4.setObjectName("ipaddrLabel_4")
        self.horizontalLayout_24.addWidget(self.ipaddrLabel_4)
        self.lipaddrlineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lipaddrlineEdit_4.sizePolicy().hasHeightForWidth())
        self.lipaddrlineEdit_4.setSizePolicy(sizePolicy)
        self.lipaddrlineEdit_4.setObjectName("lipaddrlineEdit_4")
        self.horizontalLayout_24.addWidget(self.lipaddrlineEdit_4)
        self.lportLabel_4 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.lportLabel_4.setFont(font)
        self.lportLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lportLabel_4.setObjectName("lportLabel_4")
        self.horizontalLayout_24.addWidget(self.lportLabel_4)
        self.lport_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lport_4.setObjectName("lport_4")
        self.horizontalLayout_24.addWidget(self.lport_4)
        self.reboundLabel_4 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.reboundLabel_4.setFont(font)
        self.reboundLabel_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reboundLabel_4.setObjectName("reboundLabel_4")
        self.horizontalLayout_24.addWidget(self.reboundLabel_4)
        self.reboundCombo_4 = QtWidgets.QComboBox(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.reboundCombo_4.sizePolicy().hasHeightForWidth())
        self.reboundCombo_4.setSizePolicy(sizePolicy)
        self.reboundCombo_4.setEditable(True)
        self.reboundCombo_4.setObjectName("reboundCombo_4")
        self.horizontalLayout_24.addWidget(self.reboundCombo_4)
        self.reboundButton_4 = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.reboundButton_4.setFont(font)
        self.reboundButton_4.setObjectName("reboundButton_4")
        self.horizontalLayout_24.addWidget(self.reboundButton_4)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.mainFrame_5 = QtWidgets.QFrame(self.tab_6)
        self.mainFrame_5.setGeometry(QtCore.QRect(10, 7, 1181, 48))
        self.mainFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame_5.setObjectName("mainFrame_5")
        self._5 = QtWidgets.QGridLayout(self.mainFrame_5)
        self._5.setObjectName("_5")
        self.targetlineEdit_5 = QtWidgets.QLineEdit(self.mainFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetlineEdit_5.sizePolicy().hasHeightForWidth())
        self.targetlineEdit_5.setSizePolicy(sizePolicy)
        self.targetlineEdit_5.setObjectName("targetlineEdit_5")
        self._5.addWidget(self.targetlineEdit_5, 0, 3, 1, 2)
        self.payloadCombo_5 = QtWidgets.QComboBox(self.mainFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payloadCombo_5.sizePolicy().hasHeightForWidth())
        self.payloadCombo_5.setSizePolicy(sizePolicy)
        self.payloadCombo_5.setEditable(True)
        self.payloadCombo_5.setObjectName("payloadCombo_5")
        self._5.addWidget(self.payloadCombo_5, 0, 1, 1, 1)
        self.emptyButton_5 = QtWidgets.QPushButton(self.mainFrame_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.emptyButton_5.setFont(font)
        self.emptyButton_5.setObjectName("emptyButton_5")
        self._5.addWidget(self.emptyButton_5, 0, 6, 1, 1)
        self.payloadLabel_5 = QtWidgets.QLabel(self.mainFrame_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.payloadLabel_5.setFont(font)
        self.payloadLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.payloadLabel_5.setObjectName("payloadLabel_5")
        self._5.addWidget(self.payloadLabel_5, 0, 0, 1, 1)
        self.CheckButton_5 = QtWidgets.QPushButton(self.mainFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckButton_5.sizePolicy().hasHeightForWidth())
        self.CheckButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.CheckButton_5.setFont(font)
        self.CheckButton_5.setObjectName("CheckButton_5")
        self._5.addWidget(self.CheckButton_5, 0, 5, 1, 1)
        self.targetLabel_5 = QtWidgets.QLabel(self.mainFrame_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.targetLabel_5.setFont(font)
        self.targetLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.targetLabel_5.setObjectName("targetLabel_5")
        self._5.addWidget(self.targetLabel_5, 0, 2, 1, 1)
        self.tabWidget_6 = QtWidgets.QTabWidget(self.tab_6)
        self.tabWidget_6.setGeometry(QtCore.QRect(10, 147, 1181, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.tabWidget_6.sizePolicy().hasHeightForWidth())
        self.tabWidget_6.setSizePolicy(sizePolicy)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.tab_29)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.basicInfoTextEdit_5 = QtWidgets.QTextEdit(self.tab_29)
        self.basicInfoTextEdit_5.setOverwriteMode(True)
        self.basicInfoTextEdit_5.setObjectName("basicInfoTextEdit_5")
        self.verticalLayout_22.addWidget(self.basicInfoTextEdit_5)
        self.tabWidget_6.addTab(self.tab_29, "")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab_30)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.commandLabel_17 = QtWidgets.QLabel(self.tab_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_17.sizePolicy().hasHeightForWidth())
        self.commandLabel_17.setSizePolicy(sizePolicy)
        self.commandLabel_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_17.setObjectName("commandLabel_17")
        self.horizontalLayout_25.addWidget(self.commandLabel_17)
        self.commandCombo_9 = QtWidgets.QComboBox(self.tab_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo_9.sizePolicy().hasHeightForWidth())
        self.commandCombo_9.setSizePolicy(sizePolicy)
        self.commandCombo_9.setEditable(True)
        self.commandCombo_9.setObjectName("commandCombo_9")
        self.horizontalLayout_25.addWidget(self.commandCombo_9)
        self.commondButton_21 = QtWidgets.QPushButton(self.tab_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_21.sizePolicy().hasHeightForWidth())
        self.commondButton_21.setSizePolicy(sizePolicy)
        self.commondButton_21.setObjectName("commondButton_21")
        self.horizontalLayout_25.addWidget(self.commondButton_21)
        self.verticalLayout_24.addLayout(self.horizontalLayout_25)
        self.commandBasicInfoTextEdit_13 = QtWidgets.QTextEdit(self.tab_30)
        self.commandBasicInfoTextEdit_13.setAccessibleDescription("")
        self.commandBasicInfoTextEdit_13.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_13.setPlaceholderText("")
        self.commandBasicInfoTextEdit_13.setObjectName("commandBasicInfoTextEdit_13")
        self.verticalLayout_24.addWidget(self.commandBasicInfoTextEdit_13)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        self.tabWidget_6.addTab(self.tab_30, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.tab_31)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.commandLabel_18 = QtWidgets.QLabel(self.tab_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_18.sizePolicy().hasHeightForWidth())
        self.commandLabel_18.setSizePolicy(sizePolicy)
        self.commandLabel_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_18.setObjectName("commandLabel_18")
        self.horizontalLayout_27.addWidget(self.commandLabel_18)
        self.localListenEdit_10 = QtWidgets.QLineEdit(self.tab_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_10.sizePolicy().hasHeightForWidth())
        self.localListenEdit_10.setSizePolicy(sizePolicy)
        self.localListenEdit_10.setObjectName("localListenEdit_10")
        self.horizontalLayout_27.addWidget(self.localListenEdit_10)
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_31)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_27.addWidget(self.checkBox_5)
        self.commondButton_22 = QtWidgets.QPushButton(self.tab_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_22.sizePolicy().hasHeightForWidth())
        self.commondButton_22.setSizePolicy(sizePolicy)
        self.commondButton_22.setObjectName("commondButton_22")
        self.horizontalLayout_27.addWidget(self.commondButton_22)
        self.verticalLayout_25.addLayout(self.horizontalLayout_27)
        self.commandBasicInfoTextEdit_14 = QtWidgets.QTextEdit(self.tab_31)
        self.commandBasicInfoTextEdit_14.setEnabled(True)
        self.commandBasicInfoTextEdit_14.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_14.setObjectName("commandBasicInfoTextEdit_14")
        self.verticalLayout_25.addWidget(self.commandBasicInfoTextEdit_14)
        self.horizontalLayout_26.addLayout(self.verticalLayout_25)
        self.tabWidget_6.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.tab_32)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.commandLabel_19 = QtWidgets.QLabel(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_19.sizePolicy().hasHeightForWidth())
        self.commandLabel_19.setSizePolicy(sizePolicy)
        self.commandLabel_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_19.setObjectName("commandLabel_19")
        self.horizontalLayout_29.addWidget(self.commandLabel_19)
        self.commandCombo_10 = QtWidgets.QComboBox(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandCombo_10.sizePolicy().hasHeightForWidth())
        self.commandCombo_10.setSizePolicy(sizePolicy)
        self.commandCombo_10.setEditable(True)
        self.commandCombo_10.setObjectName("commandCombo_10")
        self.horizontalLayout_29.addWidget(self.commandCombo_10)
        self.commandLabel_20 = QtWidgets.QLabel(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandLabel_20.sizePolicy().hasHeightForWidth())
        self.commandLabel_20.setSizePolicy(sizePolicy)
        self.commandLabel_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commandLabel_20.setObjectName("commandLabel_20")
        self.horizontalLayout_29.addWidget(self.commandLabel_20)
        self.localListenEdit_11 = QtWidgets.QLineEdit(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localListenEdit_11.sizePolicy().hasHeightForWidth())
        self.localListenEdit_11.setSizePolicy(sizePolicy)
        self.localListenEdit_11.setObjectName("localListenEdit_11")
        self.horizontalLayout_29.addWidget(self.localListenEdit_11)
        self.commondButton_23 = QtWidgets.QPushButton(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_23.sizePolicy().hasHeightForWidth())
        self.commondButton_23.setSizePolicy(sizePolicy)
        self.commondButton_23.setObjectName("commondButton_23")
        self.horizontalLayout_29.addWidget(self.commondButton_23)
        self.commondButton_24 = QtWidgets.QPushButton(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_24.sizePolicy().hasHeightForWidth())
        self.commondButton_24.setSizePolicy(sizePolicy)
        self.commondButton_24.setObjectName("commondButton_24")
        self.horizontalLayout_29.addWidget(self.commondButton_24)
        self.commondButton_25 = QtWidgets.QPushButton(self.tab_32)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commondButton_25.sizePolicy().hasHeightForWidth())
        self.commondButton_25.setSizePolicy(sizePolicy)
        self.commondButton_25.setObjectName("commondButton_25")
        self.horizontalLayout_29.addWidget(self.commondButton_25)
        self.verticalLayout_26.addLayout(self.horizontalLayout_29)
        self.commandBasicInfoTextEdit_15 = QtWidgets.QTextEdit(self.tab_32)
        self.commandBasicInfoTextEdit_15.setOverwriteMode(True)
        self.commandBasicInfoTextEdit_15.setObjectName("commandBasicInfoTextEdit_15")
        self.verticalLayout_26.addWidget(self.commandBasicInfoTextEdit_15)
        self.horizontalLayout_28.addLayout(self.verticalLayout_26)
        self.tabWidget_6.addTab(self.tab_32, "")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 577, 1181, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit_5.sizePolicy().hasHeightForWidth())
        self.textEdit_5.setSizePolicy(sizePolicy)
        self.textEdit_5.setObjectName("textEdit_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 70, 1181, 51))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.ipaddrLabel_5 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.ipaddrLabel_5.setFont(font)
        self.ipaddrLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel_5.setObjectName("ipaddrLabel_5")
        self.horizontalLayout_30.addWidget(self.ipaddrLabel_5)
        self.lipaddrlineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lipaddrlineEdit_5.sizePolicy().hasHeightForWidth())
        self.lipaddrlineEdit_5.setSizePolicy(sizePolicy)
        self.lipaddrlineEdit_5.setObjectName("lipaddrlineEdit_5")
        self.horizontalLayout_30.addWidget(self.lipaddrlineEdit_5)
        self.lportLabel_5 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.lportLabel_5.setFont(font)
        self.lportLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lportLabel_5.setObjectName("lportLabel_5")
        self.horizontalLayout_30.addWidget(self.lportLabel_5)
        self.lport_5 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lport_5.setObjectName("lport_5")
        self.horizontalLayout_30.addWidget(self.lport_5)
        self.reboundLabel_5 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.reboundLabel_5.setFont(font)
        self.reboundLabel_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reboundLabel_5.setObjectName("reboundLabel_5")
        self.horizontalLayout_30.addWidget(self.reboundLabel_5)
        self.reboundCombo_5 = QtWidgets.QComboBox(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.reboundCombo_5.sizePolicy().hasHeightForWidth())
        self.reboundCombo_5.setSizePolicy(sizePolicy)
        self.reboundCombo_5.setEditable(True)
        self.reboundCombo_5.setObjectName("reboundCombo_5")
        self.horizontalLayout_30.addWidget(self.reboundCombo_5)
        self.reboundButton_5 = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Kaiti SC")
        self.reboundButton_5.setFont(font)
        self.reboundButton_5.setObjectName("reboundButton_5")
        self.horizontalLayout_30.addWidget(self.reboundButton_5)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_7)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_7)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_4.addWidget(self.textEdit_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.Agent_textEdit = QtWidgets.QTextEdit(self.tab_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Agent_textEdit.sizePolicy().hasHeightForWidth())
        self.Agent_textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.Agent_textEdit.setFont(font)
        self.Agent_textEdit.setObjectName("Agent_textEdit")
        self.verticalLayout_9.addWidget(self.Agent_textEdit)
        self.horizontalLayout_11.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_37 = QtWidgets.QWidget()
        self.tab_37.setObjectName("tab_37")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_37)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ipaddrLabel_20 = QtWidgets.QLabel(self.tab_37)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.ipaddrLabel_20.setFont(font)
        self.ipaddrLabel_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel_20.setObjectName("ipaddrLabel_20")
        self.horizontalLayout_3.addWidget(self.ipaddrLabel_20)
        self.vul_lineEdit = QtWidgets.QLineEdit(self.tab_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vul_lineEdit.sizePolicy().hasHeightForWidth())
        self.vul_lineEdit.setSizePolicy(sizePolicy)
        self.vul_lineEdit.setMinimumSize(QtCore.QSize(1, 0))
        self.vul_lineEdit.setText("")
        self.vul_lineEdit.setObjectName("vul_lineEdit")
        self.horizontalLayout_3.addWidget(self.vul_lineEdit)
        self.ipaddrLabel_19 = QtWidgets.QLabel(self.tab_37)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.ipaddrLabel_19.setFont(font)
        self.ipaddrLabel_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel_19.setObjectName("ipaddrLabel_19")
        self.horizontalLayout_3.addWidget(self.ipaddrLabel_19)
        self.vul_indexpage_lineEdit = QtWidgets.QLineEdit(self.tab_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vul_indexpage_lineEdit.sizePolicy().hasHeightForWidth())
        self.vul_indexpage_lineEdit.setSizePolicy(sizePolicy)
        self.vul_indexpage_lineEdit.setText("")
        self.vul_indexpage_lineEdit.setObjectName("vul_indexpage_lineEdit")
        self.horizontalLayout_3.addWidget(self.vul_indexpage_lineEdit)
        self.ipaddrLabel_21 = QtWidgets.QLabel(self.tab_37)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.ipaddrLabel_21.setFont(font)
        self.ipaddrLabel_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipaddrLabel_21.setObjectName("ipaddrLabel_21")
        self.horizontalLayout_3.addWidget(self.ipaddrLabel_21)
        self.page_level_lineEdit = QtWidgets.QLineEdit(self.tab_37)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_level_lineEdit.sizePolicy().hasHeightForWidth())
        self.page_level_lineEdit.setSizePolicy(sizePolicy)
        self.page_level_lineEdit.setText("")
        self.page_level_lineEdit.setObjectName("page_level_lineEdit")
        self.horizontalLayout_3.addWidget(self.page_level_lineEdit)
        self.add_nav_index_data_Button = QtWidgets.QPushButton(self.tab_37)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.add_nav_index_data_Button.setFont(font)
        self.add_nav_index_data_Button.setObjectName("add_nav_index_data_Button")
        self.horizontalLayout_3.addWidget(self.add_nav_index_data_Button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.status_textEdit = QtWidgets.QTextEdit(self.tab_37)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.status_textEdit.setFont(font)
        self.status_textEdit.setObjectName("status_textEdit")
        self.verticalLayout_10.addWidget(self.status_textEdit)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_37)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_10.addWidget(self.calendarWidget)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        self.line_2 = QtWidgets.QFrame(self.tab_37)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_12.addWidget(self.line_2)
        self.tabWidget.addTab(self.tab_37, "")
        self.horizontalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1667, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.targetLabel.setBuddy(self.payloadCombo)
        self.targetLabel_3.setBuddy(self.payloadCombo)
        self.targetLabel_4.setBuddy(self.payloadCombo)
        self.targetLabel_5.setBuddy(self.payloadCombo)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(1)
        self.tabWidget_6.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROC综合漏洞RCE利用框架 by Rocky & t00ls.net 版本v1.1.1"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "导航栏"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "通用漏洞利用"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "big"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "thinkphp"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "weblogic"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "特殊漏洞利用"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "致远OA"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "漏洞管理"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "功能设置"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.targetlineEdit.setPlaceholderText(_translate("MainWindow", "http://192.168.50.122:8080"))
        self.targetLabel.setText(_translate("MainWindow", "目标地址:"))
        self.payloadLabel.setText(_translate("MainWindow", "攻击载核:"))
        self.payloadCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.emptyButton.setText(_translate("MainWindow", "清空日志"))
        self.CheckButton.setText(_translate("MainWindow", "检查"))
        self.ipaddrLabel.setText(_translate("MainWindow", "本地ip:"))
        self.lportLabel.setText(_translate("MainWindow", "端口:"))
        self.reboundLabel.setText(_translate("MainWindow", "反弹方式:"))
        self.reboundCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.reboundButton.setText(_translate("MainWindow", "执行反弹"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "基本信息"))
        self.commandLabel.setText(_translate("MainWindow", "命令执行:"))
        self.commandCombo.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commondButton.setText(_translate("MainWindow", "执行"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "命令执行"))
        self.commandLabel_2.setText(_translate("MainWindow", "文件路径:"))
        self.checkBox.setText(_translate("MainWindow", "自定义路径"))
        self.uploadFilesbutton.setText(_translate("MainWindow", "上传文件"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "文件上传"))
        self.commandLabel_3.setText(_translate("MainWindow", "线程："))
        self.threads_num.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commandLabel_4.setText(_translate("MainWindow", "文件路径:"))
        self.importButton.setText(_translate("MainWindow", "导入"))
        self.startCheckButton.setText(_translate("MainWindow", "开始"))
        self.stopCheckButton.setText(_translate("MainWindow", "停止"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "批量验证"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.targetlineEdit_2.setPlaceholderText(_translate("MainWindow", "http://192.168.50.122:8080/index.php"))
        self.targetLabel_3.setText(_translate("MainWindow", "目标地址:"))
        self.emptyButton_2.setText(_translate("MainWindow", "清空日志"))
        self.CheckButton_2.setText(_translate("MainWindow", "检查"))
        self.payloadCombo_2.setToolTip(_translate("MainWindow", "Specify your name"))
        self.payloadLabel_2.setText(_translate("MainWindow", "攻击载核:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_21), _translate("MainWindow", "基本信息"))
        self.commandLabel_10.setText(_translate("MainWindow", "文件路径:"))
        self.commandLabel_21.setText(_translate("MainWindow", "文件名称:"))
        self.uploadFilesbutton_2.setText(_translate("MainWindow", "上传文件"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_23), _translate("MainWindow", "文件上传"))
        self.commandLabel_11.setText(_translate("MainWindow", "线程："))
        self.threads_num_2.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commandLabel_12.setText(_translate("MainWindow", "文件路径:"))
        self.importButton_2.setText(_translate("MainWindow", "导入"))
        self.startCheckButton_2.setText(_translate("MainWindow", "开始"))
        self.stopCheckButton_2.setText(_translate("MainWindow", "停止"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_24), _translate("MainWindow", "批量验证"))
        self.decVule.setText(_translate("MainWindow", "解码解压"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "解码"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.targetlineEdit_4.setPlaceholderText(_translate("MainWindow", "http://192.168.50.122:8080/index.php"))
        self.payloadCombo_4.setToolTip(_translate("MainWindow", "Specify your name"))
        self.emptyButton_4.setText(_translate("MainWindow", "清空日志"))
        self.payloadLabel_4.setText(_translate("MainWindow", "攻击载核:"))
        self.CheckButton_4.setText(_translate("MainWindow", "检查"))
        self.targetLabel_4.setText(_translate("MainWindow", "目标地址:"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_25), _translate("MainWindow", "基本信息"))
        self.commandLabel_13.setText(_translate("MainWindow", "命令执行:"))
        self.commandCombo_7.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commondButton_16.setText(_translate("MainWindow", "执行"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_26), _translate("MainWindow", "命令执行"))
        self.commandLabel_14.setText(_translate("MainWindow", "文件路径:"))
        self.checkBox_4.setText(_translate("MainWindow", "自定义路径"))
        self.commondButton_17.setText(_translate("MainWindow", "上传文件"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_27), _translate("MainWindow", "文件上传"))
        self.commandLabel_15.setText(_translate("MainWindow", "线程："))
        self.commandCombo_8.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commandLabel_16.setText(_translate("MainWindow", "文件路径:"))
        self.commondButton_18.setText(_translate("MainWindow", "导入"))
        self.commondButton_19.setText(_translate("MainWindow", "开始"))
        self.commondButton_20.setText(_translate("MainWindow", "停止"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_28), _translate("MainWindow", "批量验证"))
        self.ipaddrLabel_4.setText(_translate("MainWindow", "本地ip:"))
        self.lportLabel_4.setText(_translate("MainWindow", "端口:"))
        self.reboundLabel_4.setText(_translate("MainWindow", "反弹方式:"))
        self.reboundCombo_4.setToolTip(_translate("MainWindow", "Specify your name"))
        self.reboundButton_4.setText(_translate("MainWindow", "执行反弹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "页"))
        self.targetlineEdit_5.setPlaceholderText(_translate("MainWindow", "http://192.168.50.122:8080/index.php"))
        self.payloadCombo_5.setToolTip(_translate("MainWindow", "Specify your name"))
        self.emptyButton_5.setText(_translate("MainWindow", "清空日志"))
        self.payloadLabel_5.setText(_translate("MainWindow", "攻击载核:"))
        self.CheckButton_5.setText(_translate("MainWindow", "检查"))
        self.targetLabel_5.setText(_translate("MainWindow", "目标地址:"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_29), _translate("MainWindow", "基本信息"))
        self.commandLabel_17.setText(_translate("MainWindow", "命令执行:"))
        self.commandCombo_9.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commondButton_21.setText(_translate("MainWindow", "执行"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_30), _translate("MainWindow", "命令执行"))
        self.commandLabel_18.setText(_translate("MainWindow", "文件路径:"))
        self.checkBox_5.setText(_translate("MainWindow", "自定义路径"))
        self.commondButton_22.setText(_translate("MainWindow", "上传文件"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_31), _translate("MainWindow", "文件上传"))
        self.commandLabel_19.setText(_translate("MainWindow", "线程："))
        self.commandCombo_10.setToolTip(_translate("MainWindow", "Specify your name"))
        self.commandLabel_20.setText(_translate("MainWindow", "文件路径:"))
        self.commondButton_23.setText(_translate("MainWindow", "导入"))
        self.commondButton_24.setText(_translate("MainWindow", "开始"))
        self.commondButton_25.setText(_translate("MainWindow", "停止"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_32), _translate("MainWindow", "批量验证"))
        self.ipaddrLabel_5.setText(_translate("MainWindow", "本地ip:"))
        self.lportLabel_5.setText(_translate("MainWindow", "端口:"))
        self.reboundLabel_5.setText(_translate("MainWindow", "反弹方式:"))
        self.reboundCombo_5.setToolTip(_translate("MainWindow", "Specify your name"))
        self.reboundButton_5.setText(_translate("MainWindow", "执行反弹"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "页"))
        self.textEdit_2.setHtml(_translate("MainWindow",
                                           "91xx.org|blog.91xx.org|POC、EXP提交地址：https://e.coding.net/ttsec/rocComExpRce/rocRceExp_Poc.git"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "页"))
        self.ipaddrLabel_20.setText(_translate("MainWindow", "导航栏漏洞利用索引名称:"))
        self.ipaddrLabel_19.setText(_translate("MainWindow", "导航栏选项卡联动索引:"))
        self.ipaddrLabel_21.setText(_translate("MainWindow", "设置菜单级别:"))
        self.add_nav_index_data_Button.setText(_translate("MainWindow", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_37), _translate("MainWindow", "页"))
